spring:
  datasource:
    url: jdbc:postgresql://${OPENDOOR_DB}:5432/opendoor
    driverClassName: org.postgresql.Driver
    username: opendoor
    password: opendoor
    testWhileIdle: true
    validationQuery: SELECT 1
---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/opendoor